packages:
  - 'apps/*'
  - '!apps/cli'
  - '!apps/web-verifier'
  - 'packages/*'
  - 'services/*'
  - 'modules/*'

overrides:
  qs: '>=6.14.1'

minimumReleaseAge: 0

allowBuilds:
  esbuild: true
  sharp: true
  '@nestjs/core': true
  unrs-resolver: true
  '@scarf/scarf': false
  core-js: false
